---
title: "Georgia_root_lengths_Leah"
author: "Leah Treffer"
date: "2025-11-17"
output: html_document
---

Quick analysis for Alex

Are there differences between treatments, ratios, species
Do we need three water treatments

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(boxr)
library(readr)
library(readxl)
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(lmerTest)
library(emmeans)
```

Cereal Mixtures 2025 folder id : 326957031709
Georgia Data shee file id: 2001945973910

```{r}
data <- box_read_excel(2001945973910, sheet = "Subplot level data sheet")
```

```{r}
# get just useful columns 
data_root <- data[,c("Plot", "Subplot_ID", "Ratio","Subplot_species","Treatment", "Rep", "FinalRootLength")]
data_root <- data_root[c(1:180),]

data_root$Plot <- as.character(data_root$Plot)
data_root$Subplot_ID <- as.character(data_root$Subplot_ID)
data_root$Ratio <- as.factor(data_root$Ratio)
data_root$Subplot_species <- as.factor(data_root$Subplot_species)
data_root$Treatment <- as.factor(data_root$Treatment)
data_root$Rep <- as.factor(data_root$Rep)
data_root$FinalRootLength <- as.numeric(data_root$FinalRootLength)
```

```{r}
plot(data_root$Ratio, data_root$FinalRootLength)
```

```{r}
ggplot(data_root, aes(x = Ratio,
                      y = FinalRootLength,
                      color = Subplot_species)) +
  geom_point(size = 3) +
  geom_line(aes(group = Subplot_species), size = 1.1) +
  labs(
    x = "Barley : Wheat plants in pot",
    y = "Final Root Length",
    title = "Replacement Series Plot",
    color = "Species"
  ) +
  theme_minimal(base_size = 14)
```

```{r}
library(dplyr)
library(tidyr)

data_root2 <- data_root %>%
  separate(Subplot_ID, into = c("pot", "plant"), sep = "\\.", convert = TRUE)

data_root2 <- data_root2 %>%
  group_by(pot) %>%
  arrange(plant) %>%                      # ensure correct order
  mutate(Length_flipped = rev(FinalRootLength)) %>%   # reverse the values
  ungroup()
```

```{r}
ggplot(data_root2, aes(x = Ratio,
                      y = Length_flipped,
                      color = Subplot_species)) +
  geom_point(size = 3) +
  geom_line(aes(group = Subplot_species), size = 1.1) +
  labs(
    x = "Barley : Wheat plants in pot",
    y = "Final Root Length",
    title = "Replacement Series Plot",
    color = "Species"
  ) +
  theme_minimal(base_size = 14)
```

```{r}
model1 <- lmerTest::lmer(Length_flipped ~  Subplot_species + Treatment + (1|Ratio) + (1|Rep), data = data_root2)

model2 <- lmerTest::lmer(Length_flipped ~  Subplot_species + Treatment + Ratio + (1|Rep), data = data_root2)

model3 <- lmerTest::lmer(Length_flipped ~  Subplot_species * Treatment + Ratio + (1|Rep), data = data_root2)

model4 <- lmerTest::lmer(Length_flipped ~  Subplot_species * Treatment + (1|Ratio) + (1|Rep), data = data_root2)

model5 <- lmerTest::lmer(Length_flipped ~  Subplot_species * Treatment + Ratio * Treatment + (1|Rep), data = data_root2)

model6 <- lmerTest::lmer(Length_flipped ~  Subplot_species * Treatment * Ratio + (1|Rep), data = data_root2)

AIC(model1, model2,model3,model4,model5,model6)

anova(model3,model5)
```

```{r}
model_root <- lmerTest::lmer(Length_flipped ~  Subplot_species * Treatment * Ratio + (1|Rep), data = data_root2)
summary(model_root)

#Does root length differ between species within each treatment
emmeans(model_root, pairwise ~ Subplot_species | Treatment) 
#Does root length differ between planting ratios within each treatment
emmeans(model_root, pairwise ~ Ratio | Treatment) 
#Does root length differ between species within ratio and treatment
emmeans(model_root, pairwise ~ Subplot_species | Ratio * Treatment) 

#Does root length differ between Treatment
emmeans(model_root, pairwise ~ Treatment | Ratio * Subplot_species) 

```
