---
title: "Georgia_root_lengths_Leah"
author: "Leah Treffer"
date: "2025-11-17"
output: html_document
---

Quick analysis for Alex

Are there differences between treatments, ratios, species
Do we need three water treatments

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(boxr)
library(readr)
library(readxl)
library(tidyr)
library(dplyr)
library(stringr)
library(ggplot2)
library(lmerTest)
library(emmeans)
library(multcomp)
library(kableExtra)
library(flextable)
library(tibble)
```

```{r eval=FALSE, include=FALSE}
#Cereal Mixtures 2025 folder id : 326957031709
box_auth(client_id = "bamza65junx3iksnkq2jyo8dc4xo5aok", client_secret = "Guj1WmaR4rC6FckY1TAbFWVUTNWC4lCb")
box_ls(326957031709)
```


```{r}
# Georgia Data sheet file id: 2001945973910
# Biomass data sheet file id: 2050198667244
data <- box_read_excel(2001945973910, sheet = "Subplot level data sheet")
biomass <- box_read_excel(2050198667244)
```

# Root length at termination 

```{r}
# get just useful columns 
data_root <- data[,c("Plot", "Subplot_ID", "Ratio","Subplot_species","Treatment", "Rep", "FinalRootLength")]
data_root <- data_root[c(1:180),]

data_root$Plot <- as.character(data_root$Plot)
data_root$Subplot_ID <- as.character(data_root$Subplot_ID)
data_root$Ratio <- as.factor(data_root$Ratio)
data_root$Subplot_species <- as.factor(data_root$Subplot_species)
data_root$Treatment <- as.factor(data_root$Treatment)
data_root$Rep <- as.factor(data_root$Rep)
data_root$FinalRootLength <- as.numeric(data_root$FinalRootLength)
```

```{r}
plot(data_root$Ratio, data_root$FinalRootLength)
```

```{r}
ggplot(data_root, aes(x = Ratio,
                      y = FinalRootLength,
                      color = Subplot_species)) +
  geom_point(size = 3) +
  geom_line(aes(group = Subplot_species), size = 1.1) +
  labs(
    x = "Barley : Wheat plants in pot",
    y = "Final Root Length",
    title = "Replacement Series Plot",
    color = "Species"
  ) +
  theme_minimal(base_size = 14)
```

```{r}
library(dplyr)
library(tidyr)

data_root2 <- data_root %>%
  separate(Subplot_ID, into = c("pot", "plant"), sep = "\\.", convert = TRUE)

data_root2 <- data_root2 %>%
  group_by(pot) %>%
  arrange(plant) %>%                      # ensure correct order
  mutate(Length_flipped = rev(FinalRootLength)) %>%   # reverse the values
  ungroup()
```

```{r}
ggplot(data_root2, aes(x = Ratio,
                      y = Length_flipped,
                      color = Subplot_species)) +
  geom_point(size = 3) +
  geom_line(aes(group = Subplot_species), size = 1.1) +
  labs(
    x = "Barley : Wheat plants in pot",
    y = "Final Root Length",
    title = "Replacement Series Plot",
    color = "Species"
  ) +
  theme_minimal(base_size = 14)
```

```{r}
model1 <- lmerTest::lmer(Length_flipped ~  Subplot_species + Treatment + (1|Ratio) + (1|Rep), data = data_root2)

model2 <- lmerTest::lmer(Length_flipped ~  Subplot_species + Treatment + Ratio + (1|Rep), data = data_root2)

model3 <- lmerTest::lmer(Length_flipped ~  Subplot_species * Treatment + Ratio + (1|Rep), data = data_root2)

model4 <- lmerTest::lmer(Length_flipped ~  Subplot_species * Treatment + (1|Ratio) + (1|Rep), data = data_root2)

model5 <- lmerTest::lmer(Length_flipped ~  Subplot_species * Treatment + Ratio * Treatment + (1|Rep), data = data_root2)

model6 <- lmerTest::lmer(Length_flipped ~  Subplot_species * Treatment * Ratio + (1|Rep), data = data_root2)

AIC(model1, model2,model3,model4,model5,model6)

anova(model3,model5)
```

```{r}
model_root <- lmerTest::lmer(Length_flipped ~  Subplot_species * Treatment * Ratio + (1|Rep), data = data_root2)
summary(model_root)

#Does root length differ between species within each treatment
emmeans(model_root, pairwise ~ Subplot_species | Treatment) 
#Does root length differ between planting ratios within each treatment
emmeans(model_root, pairwise ~ Ratio | Treatment) 
#Does root length differ between species within ratio and treatment
emmeans(model_root, pairwise ~ Subplot_species | Ratio * Treatment) 

#Does root length differ between Treatment
emmeans(model_root, pairwise ~ Treatment | Ratio * Subplot_species) 

```

# Biomass

```{r}
meta <- data[,c("Plot", "Ratio", "Treatment", "Rep")]
meta <- unique(meta)

biomass2 <- left_join(biomass, meta, by = "Plot")
biomass2 <- biomass2[,c("Plot", "Ratio", "Treatment", "Rep", "Species", "Type", "Weight_g")]

biomass2$Plot <- as.character(biomass2$Plot)
biomass2$Ratio <- as.factor(biomass2$Ratio)
biomass2$Treatment <- as.factor(biomass2$Treatment)
biomass2$Rep <- as.factor(biomass2$Rep)
biomass2$Species <- as.factor(biomass2$Species)
biomass2$Type <- as.factor(biomass2$Type)
biomass2$Weight_g <- as.numeric(biomass2$Weight_g)

biomass3 <- pivot_wider(biomass2,names_from = "Type", values_from = "Weight_g")
```

```{r}
qqnorm(biomass3$above)
qqline(biomass3$above)
qqnorm(sqrt(biomass3$above))
qqline(sqrt(biomass3$above))
qqnorm(log(biomass3$above))
qqline(log(biomass3$above))

qqnorm(biomass3$below)
qqline(biomass3$below)
qqnorm(sqrt(biomass3$below))
qqline(sqrt(biomass3$below))
qqnorm(log(biomass3$below))
qqline(log(biomass3$below))
```

```{r}
biomass3$above_log <- log(biomass3$above)
biomass3$below_log <- log(biomass3$below)
```

```{r eval=FALSE, include=FALSE}
# Does biomass differ between treatments 

model1 <- lmerTest::lmer(above_log ~ (1|Rep), data = biomass3)

model2 <- lmerTest::lmer(above_log ~  Treatment + (1|Rep), data = biomass3)

model3 <- lmerTest::lmer(above_log ~  Treatment + Ratio + (1|Rep), data = biomass3)

model4 <- lmerTest::lmer(above_log ~  Species + Treatment + Ratio + (1|Rep), data = biomass3)

model5 <- lmerTest::lmer(above_log ~  Species * Treatment * Ratio + (1|Rep), data = biomass3)

model6 <- lmerTest::lmer(above_log ~  Species * Ratio +  Treatment + (1|Rep), data = biomass3)

AIC(model1, model2,model3,model4,model5,model6)

anova(model5,model6)
```

## Aboveground Biomass 

```{r}
model_Abio <- lmerTest::lmer(above_log ~ Treatment * Species * Ratio + (1|Rep), data = biomass3)
anova(model_Abio)

#Does biomass differ between species within each treatment
emmeans(model_Abio, pairwise ~ Species | Treatment * Ratio) 
#Does biomass differ between planting ratios within each treatment
emmeans(model_Abio, pairwise ~ Ratio | Treatment) 
#Does biomass differ between species within ratio and treatment
emmeans(model_Abio, pairwise ~ Species | Ratio * Treatment) 
#Does biomass differ between Treatment
emmeans(model_Abio, pairwise ~ Treatment | Ratio * Species) 

```

```{r}
aov.table <- anova(model_Abio)
table = flextable(data = aov.table %>%
                    dplyr::select(NumDF, `Pr(>F)`) %>%
                    filter(`Pr(>F)` < 0.05) %>%
                    mutate(`Pr(>F)` = formatC(`Pr(>F)`, format = "e", digits = 2)) %>% 
                    rownames_to_column(" ")) 
bold(table, bold = TRUE, part = "header")

# Parwise comparison of treatment
emm <- emmeans(model_Abio, pairwise ~ Treatment | Ratio * Species) 

pairs_df <- as.data.frame(emm[["contrasts"]]) # Extract pairwise results table
# Keep only significant comparisons (p < 0.05)
sig_pairs <- pairs_df %>%
  filter(p.value < 0.06) %>%
  arrange(p.value)
# Print nicely formatted table
kbl(sig_pairs, digits = 5, caption = "Significant pairwise comparisons of Treatment (Tukey-adjusted)") %>%
  kable_classic(full_width = F, html_font = "Helvetica")

# Parwise comparison of Species*Ratio
emm_SpRat <- emmeans(model_Abio, pairwise ~ Species * Ratio | Treatment)

pairs_df <- as.data.frame(emm_SpRat[["contrasts"]]) # Extract pairwise results table
# Keep only significant comparisons (p < 0.05)
sig_pairs <- pairs_df %>%
  filter(p.value < 0.05) %>%
  arrange(Treatment, contrast)
# Print nicely formatted table
kbl(sig_pairs, digits = 5, caption = "Significant pairwise comparisons of Species - Ratio interaction (Tukey-adjusted)") %>%
  kable_classic(full_width = F, html_font = "Helvetica")
```

```{r}
# Estimated marginal means by selection category within each location
emm <- emmeans(model_Abio, pairwise ~ Treatment | Ratio * Species) 

# Pairwise comparisons (Tukey)
cld_df <- cld(emm,
              adjust = "tukey",
              Letters = letters,
              alpha = 0.05) %>%
  as.data.frame()

# merge
data2_letters <- left_join(biomass3, cld_df %>% dplyr::select(Treatment, Ratio, Species, .group),
                           by = c("Treatment", "Ratio", "Species")) %>%
  rename(letter = .group)

y_positions <- data2_letters %>%
  group_by(Treatment, Ratio, Species) %>%
  summarise(y_pos = max(above_log, na.rm = TRUE) * 1.05,
            .groups = "drop")
  
data2_letters <- left_join(data2_letters, y_positions, by = c("Treatment", "Ratio", "Species"))


# box plot with significance indicated as letters
ggplot(data2_letters,
       aes(x = Treatment, y = above_log, fill = Species)) +
  geom_boxplot() +
  facet_grid(Species~Ratio) +
  geom_text(aes(label = letter, y = y_pos+0.25),
            vjust = 0,
            size = 5,
            angle = 45,
            na.rm = TRUE) +
  labs(x = "Treatment",
       y = "Aboveground Biomass (log)",
       title = "") +
  theme_bw() +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r}
# Estimated marginal means by selection category within each location
emm_SpRat <- emmeans(model_Abio, ~ Species * Ratio | Treatment)

# Pairwise comparisons (Tukey)
cld_df <- cld(emm_SpRat,
              adjust = "tukey",
              Letters = letters,
              alpha = 0.05) %>%
  as.data.frame()

# merge
data2_letters <- left_join(biomass3, cld_df %>% dplyr::select(Treatment, Ratio, Species, .group),
                           by = c("Treatment", "Ratio", "Species")) %>%
  rename(letter = .group)

y_positions <- data2_letters %>%
  group_by(Treatment, Ratio, Species) %>%
  summarise(y_pos = max(above_log, na.rm = TRUE) * 1.05,
            .groups = "drop")
  
data2_letters <- left_join(data2_letters, y_positions, by = c("Treatment", "Ratio", "Species"))


# box plot with significance indicated as letters
ggplot(data2_letters,
       aes(x = Treatment, y = above_log, fill = Species)) +
  geom_boxplot() +
  facet_grid(Species~Ratio) +
  geom_text(aes(label = letter, y = y_pos+0.25),
            vjust = 0,
            size = 5,
            angle = 45,
            na.rm = TRUE) +
  labs(x = "Treatment",
       y = "Aboveground Biomass (log)",
       title = "") +
  theme_bw() +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

## Belowground Biomass

```{r}
model_Bbio <- lmerTest::lmer(below_log ~ Treatment * Species * Ratio + (1|Rep), data = biomass3)
anova(model_Bbio)
```


```{r}
aov.table <- anova(model_Bbio)
table = flextable(data = aov.table %>%
                    dplyr::select(NumDF, `Pr(>F)`) %>%
                    filter(`Pr(>F)` < 0.05) %>%
                    mutate(`Pr(>F)` = formatC(`Pr(>F)`, format = "e", digits = 2)) %>% 
                    rownames_to_column(" ")) 
bold(table, bold = TRUE, part = "header")

# Parwise comparison of Species*Ratio
emm_SpRat <- emmeans(model_Bbio, pairwise ~ Species * Ratio | Treatment)

pairs_df <- as.data.frame(emm_SpRat[["contrasts"]]) # Extract pairwise results table
# Keep only significant comparisons (p < 0.05)
sig_pairs <- pairs_df %>%
  filter(p.value < 0.05) %>%
  arrange(Treatment, contrast)
# Print nicely formatted table
kbl(sig_pairs, digits = 5, caption = "Significant pairwise comparisons of Species - Ratio interaction (Tukey-adjusted)") %>%
  kable_classic(full_width = F, html_font = "Helvetica")
```


```{r}
# Estimated marginal means by selection category within each location
emm_SpRat <- emmeans(model_Bbio, pairwise ~ Ratio * Species | Treatment)

# Pairwise comparisons (Tukey)
cld_df <- cld(emm_SpRat,
              adjust = "tukey",
              Letters = letters,
              alpha = 0.05) %>%
  as.data.frame()

# merge
data2_letters <- left_join(biomass3, cld_df %>% dplyr::select(Treatment, Ratio, Species, .group),
                           by = c("Treatment", "Ratio", "Species")) %>%
  rename(letter = .group)

y_positions <- data2_letters %>%
  group_by(Treatment, Ratio, Species) %>%
  summarise(y_pos = max(below_log, na.rm = TRUE) * 1.05,
            .groups = "drop")
  
data2_letters <- left_join(data2_letters, y_positions, by = c("Treatment", "Ratio", "Species"))


# box plot with significance indicated as letters
ggplot(data2_letters,
       aes(x = Treatment, y = below_log, fill = Species)) +
  geom_boxplot() +
  facet_grid(Species~Ratio) +
  geom_text(aes(label = letter, y = y_pos+0.25),
            vjust = 0,
            size = 5,
            angle = 45,
            na.rm = TRUE) +
  labs(x = "Treatment",
       y = "Belowground Biomass (log)",
       title = "") +
  theme_bw() +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```


## Biomass Ratio

```{r}
biomass3$Abv_Blw <- biomass3$above / biomass3$below

qqnorm(biomass3$Abv_Blw)
qqline(biomass3$Abv_Blw)
qqnorm(sqrt(biomass3$Abv_Blw))
qqline(sqrt(biomass3$Abv_Blw))
qqnorm(log(biomass3$Abv_Blw))
qqline(log(biomass3$Abv_Blw))

biomass3$Abv_Blw_log <- log(biomass3$Abv_Blw)
```

```{r}
model_bio <- lmerTest::lmer(Abv_Blw_log ~ Treatment * Species * Ratio + (1|Rep), data = biomass3)
anova(model_bio)
```

```{r}
aov.table <- anova(model_bio)
table = flextable(data = aov.table %>%
                    dplyr::select(NumDF, `Pr(>F)`) %>%
                    filter(`Pr(>F)` < 0.05) %>%
                    mutate(`Pr(>F)` = formatC(`Pr(>F)`, format = "e", digits = 2)) %>% 
                    rownames_to_column(" ")) 
bold(table, bold = TRUE, part = "header")

# Parwise comparison of Treatment
emm <- emmeans(model_bio, pairwise ~ Treatment | Species * Ratio)

pairs_df <- as.data.frame(emm[["contrasts"]]) # Extract pairwise results table
# Keep only significant comparisons (p < 0.05)
sig_pairs <- pairs_df %>%
  filter(p.value < 0.05) %>%
  arrange(Species, Ratio)
# Print nicely formatted table
kbl(sig_pairs, digits = 5, caption = "Significant pairwise comparisons of Treatment (Tukey-adjusted)") %>%
  kable_classic(full_width = F, html_font = "Helvetica")

# Parwise comparison of Species

```

```{r}
# Estimated marginal means by selection category within each location
emm <- emmeans(model_bio, ~ Treatment | Species * Ratio)

# Pairwise comparisons (Tukey)
cld_df <- cld(emm,
              adjust = "tukey",
              Letters = letters,
              alpha = 0.05) %>%
  as.data.frame()

# merge
data2_letters <- left_join(biomass3, cld_df %>% dplyr::select(Treatment, Ratio, Species, .group),
                           by = c("Treatment", "Ratio", "Species")) %>%
  rename(letter = .group)

y_positions <- data2_letters %>%
  group_by(Treatment, Ratio, Species) %>%
  summarise(y_pos = max(Abv_Blw_log, na.rm = TRUE) * 1.05,
            .groups = "drop")
  
data2_letters <- left_join(data2_letters, y_positions, by = c("Treatment", "Ratio", "Species"))

# box plot with significance indicated as letters
ggplot(data2_letters,
       aes(x = Treatment, y = Abv_Blw_log, fill = Species)) +
  geom_boxplot() +
  facet_grid(Species~Ratio) +
  geom_text(aes(label = letter, y = y_pos+0.25),
            vjust = 0,
            size = 5,
            angle = 45,
            na.rm = TRUE) +
  labs(x = "Treatment",
       y = "Belowground Biomass (log)",
       title = "") +
  theme_bw() +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```


## Total Biomass

```{r}
biomass3$tot_biomass <- biomass3$above + biomass3$below

qqnorm(biomass3$tot_biomass)
qqline(biomass3$tot_biomass)
qqnorm(sqrt(biomass3$tot_biomass))
qqline(sqrt(biomass3$tot_biomass))
qqnorm(log(biomass3$tot_biomass))
qqline(log(biomass3$tot_biomass))

biomass3$totbiomass_log <- log(biomass3$tot_biomass)
```

```{r}
model_totbio <- lmerTest::lmer(totbiomass_log ~ Treatment * Species * Ratio + (1|Rep), data = biomass3)
anova(model_totbio)
```

```{r}
aov.table <- anova(model_totbio)
table = flextable(data = aov.table %>%
                    dplyr::select(NumDF, `Pr(>F)`) %>%
                    filter(`Pr(>F)` < 0.05) %>%
                    mutate(`Pr(>F)` = formatC(`Pr(>F)`, format = "e", digits = 2)) %>% 
                    rownames_to_column(" ")) 
bold(table, bold = TRUE, part = "header")

# Parwise comparison of Species Ratio Interaction
emm <- emmeans(model_totbio, pairwise ~ Species * Ratio | Treatment)

pairs_df <- as.data.frame(emm[["contrasts"]]) # Extract pairwise results table
# Keep only significant comparisons (p < 0.05)
sig_pairs <- pairs_df %>%
  filter(p.value < 0.05) %>%
  arrange(Treatment)
# Print nicely formatted table
kbl(sig_pairs, digits = 5, caption = "Significant pairwise comparisons of Species * Ratio Interaction (Tukey-adjusted)") %>%
  kable_classic(full_width = F, html_font = "Helvetica")

```

```{r}
# Estimated marginal means by selection category within each location
emm <- emmeans(model_totbio, ~ Species * Ratio | Treatment)

# Pairwise comparisons (Tukey)
cld_df <- cld(emm,
              adjust = "tukey",
              Letters = letters,
              alpha = 0.05) %>%
  as.data.frame()

# merge
data2_letters <- left_join(biomass3, cld_df %>% dplyr::select(Treatment, Ratio, Species, .group),
                           by = c("Treatment", "Ratio", "Species")) %>%
  rename(letter = .group)

y_positions <- data2_letters %>%
  group_by(Treatment, Ratio, Species) %>%
  summarise(y_pos = max(totbiomass_log, na.rm = TRUE) * 1.05,
            .groups = "drop")
  
data2_letters <- left_join(data2_letters, y_positions, by = c("Treatment", "Ratio", "Species"))

# box plot with significance indicated as letters
ggplot(data2_letters,
       aes(x = Treatment, y = totbiomass_log, fill = Species)) +
  geom_boxplot() +
  facet_grid(Species~Ratio) +
  geom_text(aes(label = letter, y = y_pos+0.2),
            vjust = 0,
            size = 5,
            angle = 45,
            na.rm = TRUE) +
  labs(x = "Treatment",
       y = "Total Biomass (log)",
       title = "") +
  theme_bw() +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```




# Relative Yield

```{r}
# Calculate monoculture means
mono <- biomass3 %>%
  group_by(Treatment) %>%
  summarise(barley_mono = mean(tot_biomass[Ratio=="4:0"]),
            wheat_mono = mean(tot_biomass[Ratio=="0:4"]))
```

```{r}
data <- biomass3 %>%
  dplyr::select("Plot","Ratio","Treatment","Rep","Species","tot_biomass")%>%
  pivot_wider(names_from = Species, values_from = tot_biomass)%>%
  left_join(mono, by="Treatment") %>%
  mutate(RY_barley = barley / barley_mono,
         RY_wheat = wheat / wheat_mono,
         RYT = RY_barley + RY_wheat)
```

```{r}

df_long <- data %>%
  pivot_longer(
    cols = c(RY_barley, RY_wheat),
    names_to = "Species",
    values_to = "RY"
  )

ggplot(df_long, aes(
  x = Ratio,
  y = RY,
  color = Species
)) +
  geom_point(size = 3) +
  geom_line(aes(group = interaction(Species, Treatment, Rep))) +
  labs(
    x = "Proportion Species 1",
    y = "Relative Yield (RY)",
    color = "Species"
  ) +
  theme_minimal()+
  geom_hline(yintercept = 1, linetype = "dashed")+
  facet_wrap(~ Treatment)

```

## Replacement Series 

```{r}
# expected yield
data2 <- data %>%
  mutate(Prop_barley = case_when(
    Ratio == '4:0' ~ 1,
    Ratio == '3:1' ~ 0.75,
    Ratio == '2:2' ~ 0.5,
    Ratio == '1:3' ~ 0.25,
    Ratio == '0:4' ~ 0
  ))%>%
  mutate(Prop_wheat = case_when(
    Ratio == '4:0' ~ 0,
    Ratio == '3:1' ~ 0.25,
    Ratio == '2:2' ~ 0.5,
    Ratio == '1:3' ~ 0.75,
    Ratio == '0:4' ~ 1
  ))%>%
  mutate(
    expected_barley = Prop_barley * barley_mono,
    expected_wheat = Prop_wheat * wheat_mono
  )

```

```{r}
plot_df <- data2 %>%
  dplyr::select(Treatment, Ratio, barley, wheat, expected_barley, expected_wheat) %>%
  pivot_longer(
    cols = c(barley, wheat, expected_barley, expected_wheat),
    names_to = "Type",
    values_to = "Yield"
  ) %>%
  mutate(
    Species = ifelse(str_detect(Type, "barley"), "barley", "wheat"),
    LineType = ifelse(str_detect(Type, "^expected"), "Expected", "Observed")
  )
```

```{r}
treatment_labels <- c(
  "1" = "Treatment 1",
  "2" = "Treatment 2",
  "3" = "Treatment 3"
)

ggplot(plot_df, aes(x = Ratio, y = Yield,
                    linetype = LineType,
                    group = interaction(Species, LineType))) +
  
  geom_line(
    data = subset(plot_df, LineType == "Expected"),
    aes(linetype = LineType),
    color = "black",
    linewidth = 1
  ) +
  geom_line(
    data = subset(plot_df, LineType == "Observed"),
    aes(color = Species),
    linewidth = 1.2
  ) +
  geom_point(
    data = subset(plot_df, LineType == "Observed"),
    aes(color = Species),
    size = 2
  ) +
  
  facet_wrap(~ Treatment, labeller = labeller(Treatment = treatment_labels)) +
  
  scale_linetype_manual(values = c(
    "Observed" = "solid",
    "Expected" = "dashed"
  )) +
  
  labs(
    x = "Planting (Barley : Wheat)",
    y = "Total Biomass (g)",
    color = "Species",
    linetype = "Yield Type"
  ) +
  
  theme_minimal(base_size = 14) +
  theme(
    strip.text = element_text(size=20, face = "bold"),
    panel.background = element_blank(),   # removes gray
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

```

```{r}
obs_summary <- plot_df %>%
  filter(LineType == "Observed") %>%
  group_by(Treatment, Ratio, Species) %>%
  summarise(
    mean_yield = mean(Yield, na.rm = TRUE),
    se = sd(Yield, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )
```

```{r}


ggplot() +
  # Expected lines
  geom_line(
    data = subset(plot_df, LineType == "Expected"),
    aes(x = factor(Ratio, levels = c("0:4","1:3","2:2","3:1","4:0")), y = Yield, group = Species),
    linetype = "dashed",
    color = "black",
    linewidth = 1
  ) +
  
  # Ribbon for SE
  geom_ribbon(
    data = obs_summary,
    aes(x = Ratio, ymin = mean_yield - se, ymax = mean_yield + se, fill = Species),
    alpha = 0.2
  ) +

  # Observed mean line
  geom_line(
    data = obs_summary,
    aes(x = Ratio, y = mean_yield, color = Species, group = Species),
    linewidth = 1.3
  ) +

  geom_point(
    data = obs_summary,
    aes(x = Ratio, y = mean_yield, color = Species),
    size = 3
  ) +

  facet_wrap(~ Treatment, labeller = labeller(Treatment = treatment_labels)) +

  scale_color_manual(values = c("barley" = "#1f77b4", "wheat" = "#d62728")) +
  scale_fill_manual(values = c("barley" = "#1f77b4", "wheat" = "#d62728")) +

  labs(
    x = "Planting (Barley : Wheat)",
    y = "Total Biomass (g)",
    color = "Species",
    fill = "Species"
  ) +

  theme_minimal(base_size = 14) +
  theme(
    strip.text = element_text(size=20, face = "bold"),
    panel.background = element_blank(),   # removes gray
    panel.grid.minor = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```










